<?php

function bucks_import_menu() {

    $items['admin/config/system/product_import'] = array(
        'title' => 'Bucks Custom Product Import Script',
        'description' => 'Custom Script to import products into Bucks 4X4 Website',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('bucks_import_form'),
        'access arguments' => array('access content'),
        'type' => MENU_NORMAL_ITEM,
    );
    return $items;
}

function bucks_import_form($node, &$form_state) {

  $form = array('#attributes' => array('enctype' => "multipart/form-data"));

  $form['file'] = array(
    '#type' => 'managed_file',
    '#title' => 'Upload your excel spreadsheet here.',
    '#required' => TRUE,
    '#upload_validators' => array(
      'file_validate_extensions' => array('xls xlsx')
    )
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Upload and Process')
  );

  return $form;
}

//function bucks_import_form_validate($form, &$form_state) {
//  $destination = file_directory_path() . "/test";
//  var_dump($destination);
//  $file = file_save_upload('file', array('file_validate_extensions' => array('xls xlsx')), $destination);
//
//  kpr($form_state);
//  var_dump($file);
//  if (isset($file->filename)) {
//    if (file_move($file, $file->filename)) {
//      drupal_write_record('files', $file, 'fid');
//      $form_state['storage']['file'] = $file;
//    } else {
//      form_set_error('file', t('Failed to write the uploaded file ot the site\s file folder.'));
//    }
//  } else {
//    form_set_error('file', t('Invalid file, only files with the extension xls, xlsx are allowed'));
//  }
//}

function bucks_import_form_submit($form, &$form_state) {

  drupal_set_message("FORM SUBMITTED");

  //kpr($form);
  //kpr($form_state);

  require_once dirname(__FILE__) . '/classes/PHPExcel/IOFactory.php';

  $file = file_load($form_state['values']['file']);
  if($file) {
    $file->status = FILE_STATUS_PERMANENT;
    file_save($file);
  }
}
//
//
//
//  foreach($content as $data) {
//    $title = $data['title'];
//    $url_path = $data['url_path'];
//    $published_Date = $data['published_Date'];
//    $tags = $data['tags'];
//    $tag = explode(',', $tags);
//    $image = $data['image'];
//    $keywords = $data['keywords'];
//    $description = $data['description'];
//    $content = $data['content'];
//
//    $createdDate = strtotime($published_Date);
//    $createdDate1 = date("Y-m-d", $createdDate);
//
//    //Get Image
//    $imageURL = $serverURL.$image;
//    $filename = basename($imageURL);
//    $image = file_get_contents($imageURL);
//    $file = file_save_data($image, 'public://'.$filename, FILE_EXISTS_RENAME);
//
//    //Create the Node
//    $node = new stdClass();
//    $node->title = $title;
//    $node->type = "article";
//    node_object_prepare($node);
//    $node->language = LANGUAGE_NONE;
//    $node->uid = '13';
//    $node->status = 1;
//    $node->promote = 0;
//    $node->comment = 0;
//
//    $node->created = $createdDate;
//
//    $vid = taxonomy_vocabulary_machine_name_load("Tags");
//    foreach($tag as $item) {
//        $tax = taxonomy_get_term_by_name($item, $vocabulary = NULL);
//        if($tax) {
//            foreach($tax as $data) {
//                $node->field_tags[$node->language][]['tid'] = $data->tid;
//            }
//        } else {
//            $term = new stdClass();
//            $term->name = $item;
//            $term->vid = $vid->vid;
//            taxonomy_term_save($term);
//            $node->field_tags[$node->language][]['tid'] = $term->tid;
//        }
//    }
//    $node->field_meta_description['und'][0]['metatags_quick'] = $description;
//    $node->field_meta_keywords['und'][0]['metatags_quick'] = $keywords;
//    $node->field_body['und'][0]['value'] = $content;
//    $node->field_body['und'][0]['format'] = 'full_html';
//    $node->body['und'][0]['format'] = 'full_html';
//    $node->body['und'][0]['safe_value'] = $content;
//    $node->body['und'][0]['value'] = $content;
//    $node->field_image['und'][0]['fid'] = $file->fid;
//
//    node_save($node);
//  }
//  return " ";
//}


?>